add device! functions for FixedAdmittance
NREL-SIIP/PowerSimulationsDynamics.jl pull request #109
Opened 2021-07-27 22:06 UTC by m-bossart

2021-07-28 22:13 UTC, rodrigomha requested changes

2021-07-28 22:13 UTC, rodrigomha commented on src/models/load_models.jl
> +    current_r[1] += -(voltage_r[1] * G + voltage_i[1] * B)  #in system pu flowing out
This does not seem right:
From what I understand, the current going into the admittance can be computed as:
I = -YV = -(G+jB)(Vr+jVi) = -(GVr - BVi) - j(GVi + BVr)
The term BVi seems to be with a different sign.

Also we need a test using a Fixed Admittance to pass the codecov/patch requirement.

2021-07-28 22:29 UTC, jd-lara commented on src/models/load_models.jl
> +    current_r[1] += -(voltage_r[1] * G + voltage_i[1] * B)  #in system pu flowing out
@rodrigomha correct, the formula needs to be modified.

2021-08-02 19:49 UTC, m-bossart commented
Good catch, does the test need to include a comparison to psse/pscad or just build and solve a system with a fixed admittance?

2021-08-03 00:54 UTC, jd-lara commented
> Good catch, does the test need to include a comparison to psse/pscad or just build and solve a system with a fixed admittance?

For now just make a test that runs a case with the FixedAdmittance we can compare with pss/e later

2021-08-03 17:36 UTC, m-bossart commented
I'm seeing some behavior that I can't explain when solving the power flow for a system with a FixedAdmittance. I'm using the version with the previous typo corrected. I thought that the two display statements would give the same bus voltages but the solution is different. My understanding is that the `Simulation!()` call would solve the power flow and update the system voltages and power references and the `solve_powerflow()` call would give the same result. Any thoughts on what the issue could be? When I remove the FixedAdmittance the results are the same. 
```
using Pkg
Pkg.activate(".")
using Revise
using OrdinaryDiffEq
using PowerSystems
using PowerSimulationsDynamics
include("../models/DynamicComponents.jl")

sys = System("cases/IEEE 14 bus_modified_33.raw")
#sys = System("cases/IEEE 14 bus_modified_33_RemoveFixedAdmittance.raw")

for g in get_components(ThermalStandard,sys)
    inv_case = inv_case78(get_name(g))
    add_component!(sys, inv_case, g)
end

sim = Simulation!(MassMatrixModel, sys, pwd(), (0.0,1.0))
display(solve_powerflow(sys)["bus_results"])
display(get_initial_conditions(sim)["Vm"])
```

2021-08-03 17:54 UTC, rodrigomha commented
> I'm seeing some behavior that I can't explain when solving the power flow for a system with a FixedAdmittance. I'm using the version with the previous typo corrected. I thought that the two display statements would give the same bus voltages but the solution is different. My understanding is that the `Simulation!()` call would solve the power flow and update the system voltages and power references and the `solve_powerflow()` call would give the same result. Any thoughts on what the issue could be? When I remove the FixedAdmittance the results are the same.
> 
> ```
> using Pkg
> Pkg.activate(".")
> using Revise
> using OrdinaryDiffEq
> using PowerSystems
> using PowerSimulationsDynamics
> include("../models/DynamicComponents.jl")
> 
> sys = System("cases/IEEE 14 bus_modified_33.raw")
> #sys = System("cases/IEEE 14 bus_modified_33_RemoveFixedAdmittance.raw")
> 
> for g in get_components(ThermalStandard,sys)
>     inv_case = inv_case78(get_name(g))
>     add_component!(sys, inv_case, g)
> end
> 
> sim = Simulation!(MassMatrixModel, sys, pwd(), (0.0,1.0))
> display(solve_powerflow(sys)["bus_results"])
> display(get_initial_conditions(sim)["Vm"])
> ```

Okay, I have an idea. Maybe everything we are doing is not necessary. Can you check if the Ybus is different with/without the FixedAdmittance? If is different, then we don't need the add_device function, since the Ybus is used directly in the Kirchoff Law equations to compute the flow into the bus.

2021-08-03 18:00 UTC, jd-lara commented
> I'm seeing some behavior that I can't explain when solving the power flow for a system with a FixedAdmittance. I'm using the version with the previous typo corrected. I thought that the two display statements would give the same bus voltages but the solution is different. My understanding is that the `Simulation!()` call would solve the power flow and update the system voltages and power references and the `solve_powerflow()` call would give the same result. Any thoughts on what the issue could be? When I remove the FixedAdmittance the results are the same.
> 
> ```
> using Pkg
> Pkg.activate(".")
> using Revise
> using OrdinaryDiffEq
> using PowerSystems
> using PowerSimulationsDynamics
> include("../models/DynamicComponents.jl")
> 
> sys = System("cases/IEEE 14 bus_modified_33.raw")
> #sys = System("cases/IEEE 14 bus_modified_33_RemoveFixedAdmittance.raw")
> 
> for g in get_components(ThermalStandard,sys)
>     inv_case = inv_case78(get_name(g))
>     add_component!(sys, inv_case, g)
> end
> 
> sim = Simulation!(MassMatrixModel, sys, pwd(), (0.0,1.0))
> display(solve_powerflow(sys)["bus_results"])
> display(get_initial_conditions(sim)["Vm"])
> ```

It could be the admittance vs power modeling between them. I think the power flow assumes that the fixed admittance

2021-08-03 18:52 UTC, m-bossart commented
@rodrigomha The Ybus is different, so I think you are right that we do not need add_device for the FixedAdmittance

2021-08-03 22:25 UTC, jd-lara commented
@m-bossart if you think this is not needed we can close the PR and revisit this later if we want to model the loads differently

2021-08-03 22:55 UTC, closed without merging