Add REPCA, REECB, REGCA
NREL-SIIP/PowerSimulationsDynamics.jl pull request #114
Opened 2021-08-21 00:52 UTC by rodrigomha

To do:
Documentation

2021-08-21 02:51 UTC, jd-lara requested changes
There are several places that need to remove the stale commented code and unnecessary variable references `x = y`. 

My main concern with the PR is that there are large blocks of code for handling the flags that need to be moved to functions I am not sure if the compiler is correctly inferring everything inside of those large blocks and we need to make sure that we aren't creating large performance penalties with that. 

I made comments in the places I saw weird things but there might be others that need changes.

2021-08-21 02:51 UTC, jd-lara commented on src/initialization/inverter_components/init_inner.jl
> +    if PSY.get_V_ref0(inner_control) == 0.0
we probably want a warning here

2021-08-21 02:51 UTC, jd-lara commented on src/initialization/inverter_components/init_outer.jl
> +    #Obtain external states inputs for component
remove stale commented code

2021-08-21 02:51 UTC, jd-lara commented on src/initialization/inverter_components/init_outer.jl
> +    if VC_Flag == 0 && Ref_Flag == 0 && PF_Flag == 0 && V_Flag == 1
These large chunks of code inside the if-else statements should be abstracted into separate functions and call them at the if-else comparison. Before we merge we should check the type stability of these functions.

2021-08-21 02:51 UTC, jd-lara commented on src/models/inverter_models/converter_models.jl
> +    #external_ix = get_input_port_ix(dynamic_device, PSY.RenewableEnergyConverterTypeA)
remove stale commented out code

2021-08-21 02:51 UTC, jd-lara commented on src/models/inverter_models/converter_models.jl
> +    #Ir_filt_internal = Ir_filt * cos(θ) + Ii_filt * sin(θ)
ditto

2021-08-21 02:51 UTC, jd-lara commented on src/models/inverter_models/converter_models.jl
> +    G_lv = get_LV_current_gain(V_t, Lv_pnt0, Lv_pnt1)
I don't follow what is happening here.  `Rp_dn` and `Rp_up` are defined and then redefined in 111 and later used in the clamp. This code should also be abstracted into functions.

2021-08-21 02:51 UTC, jd-lara commented on src/models/inverter_models/frequency_estimator_models.jl
> +    #V_tR = get_inner_vars(dynamic_device)[Vr_inv_var]
Remove stale commented code.

2021-08-21 02:51 UTC, jd-lara commented on src/models/inverter_models/frequency_estimator_models.jl
> +    #V_tR = get_inner_vars(dynamic_device)[Vr_inv_var]
remove staled commented code

2021-08-21 02:51 UTC, jd-lara commented on src/models/inverter_models/inner_control_models.jl
> +    #Obtain external states inputs for component
Remove stale commented code

2021-08-21 02:51 UTC, jd-lara commented on src/models/inverter_models/outer_control_models.jl
> +    end
Abstract the code blocks inside of the if-else into other functions

2021-08-21 02:51 UTC, jd-lara commented on src/models/saturation_models.jl
> +    Iq_max = I_max
These variable assignments are unnecessary

2021-08-21 02:51 UTC, jd-lara commented on src/models/inverter_models/converter_models.jl
> +    Ip_sat = Ip
Not necessary to make this variable definition.

2021-08-21 02:51 UTC, jd-lara commented on src/models/inverter_models/converter_models.jl
> +    Ii_cnv = Id_cnv * sin(θ) + Iq_cnv * cos(θ)
This portion needs to be refactored. `Rq_dn` and `Rq_up` are overwritten later.

2021-08-21 02:51 UTC, jd-lara commented on src/models/inverter_models/converter_models.jl
> +        return real(V_cnv), imag(V_cnv)
This is another place that we should be doing the complex calculations directly

2021-08-21 02:51 UTC, jd-lara commented on src/models/inverter_models/filter_models.jl
> +        Zmag = rf^2 + lf^2
```suggestion
        Zmag_squared = rf^2 + lf^2
```

2021-08-21 02:51 UTC, jd-lara commented on src/models/inverter_models/outer_control_models.jl
> +    # To do: Obtain proper frequency for a plant. For now using the system frequency.
also not necessary to double assign variable

2021-08-21 02:51 UTC, jd-lara commented on src/models/inverter_models/outer_control_models.jl
> +    state_ct = 1
We have a function `PSY.get_state_count` that takes into account the number of states in the device depending on the flags already. We should use that instead.

2021-08-21 02:51 UTC, jd-lara commented on src/models/inverter_models/outer_control_models.jl
> +    p_ext = p_elec_out
another double assignment.

2021-08-21 02:51 UTC, jd-lara commented on src/models/inverter_models/outer_control_models.jl
> +        get_inner_vars(dynamic_device)[Iq_oc_var] = Q_ext / max(Vt_filt, 0.01)
make the `0.01` a const in the definitions file and include a comment about where it comes from. We can name it `VOLTAGE_DIVISION_LOWER_BOUND = 0.01`

2021-08-21 02:51 UTC, jd-lara commented on src/post_processing/post_proc_inverter.jl
> +function _output_current(
Check these functions are type stable with `@code_warn` otherwise the additional abstraction doesn't help.

2021-08-28 01:12 UTC, rodrigomha commented on src/initialization/inverter_components/init_filter.jl
> +    V = V_R + V_I * 1im
I'll update in a future PR for all initialization devices (both machines and filters).

2021-08-28 01:22 UTC, rodrigomha commented on src/initialization/inverter_components/init_inner.jl
> +    if PSY.get_V_ref0(inner_control) == 0.0
Add PSS/E behavior commentary on this

2021-08-28 01:38 UTC, rodrigomha commented on src/models/inverter_models/converter_models.jl
> +    G_lv = get_LV_current_gain(V_t, Lv_pnt0, Lv_pnt1)
```Julia
Rp_dn = Ip >= 0 : -Inf : -Rrpwr
```

2021-08-28 01:41 UTC, rodrigomha commented on src/models/saturation_models.jl
> +    Iq_max = I_max
Add comment that X,Y,Z should be the same when is working properly.

2021-08-28 01:49 UTC, rodrigomha commented on src/models/inverter_models/converter_models.jl
> +    Ip_sat = Ip
ditto other case

2021-08-28 01:49 UTC, rodrigomha commented on src/models/inverter_models/converter_models.jl
> +    Ii_cnv = Id_cnv * sin(θ) + Iq_cnv * cos(θ)
ditto

2021-09-01 02:14 UTC, rodrigomha commented on src/post_processing/post_proc_inverter.jl
> +function _output_current(
I haven't checked this yet, but we should do it in a next PR that do some cleaning also in Complex Calculations

2021-09-02 16:46 UTC, jd-lara approved these changes
@rodrigomha this PR is now too big. We should merge as it is and address some of the pending improvements in subsequent PR's

2021-09-02 20:58 UTC, rodrigomha commented
> @rodrigomha this PR is now too big. We should merge as it is and address some of the pending improvements in subsequent PR's

Agree with this. Let's go with the merge and we'll fix some of the remaining issues in future PRs

2021-09-02 20:59 UTC, merged