Inclusion of integrators to common_controls
NREL-SIIP/PowerSimulationsDynamics.jl pull request #193
Opened 2022-03-01 19:30 UTC by tavovalmo

I have included two integrators with windup and anti-windup limiters.

2022-03-01 20:42 UTC, jd-lara commented
@tavovalmo thanks for the contribution. We are just missing unit tests for these integrators. Do you mind adding them?

2022-03-01 20:43 UTC, jd-lara commented on src/models/common_controls.jl
> +    binary_logic = ((y >= y_max) && (dydt_scaled > 0)) || ((y <= y_min) && (dydt_scaled < 0)) ? 0.0 : 1.0
@rodrigomha we need to check if this syntax is type stable

2022-03-01 20:48 UTC, rodrigomha requested changes
It is not required to have the PSID part in PSID.ACCEPTED_REAL_TYPES.

Regarding the tests, it may be not required for now if we plan to add them in a new AVR model. Alternatively we can add them in test_base to test type stability.

2022-03-06 20:34 UTC, closed without merging

2022-03-07 17:57 UTC, jd-lara commented
@tavovalmo why did you close this PR? it just required some tests to be merged.

2022-03-07 23:08 UTC, tavovalmo commented
I eliminated the branch after I merged the changes in my remote repo. It seems that this action closed the PR. Sorry. I will create a new one.