Add ZIP Load model
NREL-SIIP/PowerSimulationsDynamics.jl pull request #204
Opened 2022-04-06 02:40 UTC by rodrigomha

To do: ZIP load tests

Note that this PR now considers the loads read from PSY as ConstantPower. The tests have been updated to transform the loads to ConstantImpedance.

2022-04-07 00:48 UTC, jd-lara requested changes

2022-04-07 00:48 UTC, jd-lara commented on src/base/device_wrapper.jl
> +# TO DO: We should remove this wrapper
We should remove this now, I think that if the tests pass after removing we are ok

2022-04-07 00:48 UTC, jd-lara commented on src/base/device_wrapper.jl
> +struct ZIPLoadWrapper
Since so many fields in this struct are RefValue, we can just make the struct mutable.

2022-04-07 00:48 UTC, jd-lara commented on src/base/device_wrapper.jl
> +            error("Not supported load in $(PSY.get_number(bus)) named $(PSY.get_name(ld))")
```suggestion
            error("Not supported load model in $(PSY.get_number(bus)) named $(PSY.get_name(ld))")
```

2022-04-07 00:48 UTC, jd-lara commented on src/base/device_wrapper.jl
>  get_device(wrapper::StaticWrapper) = wrapper.device
move code up, it is mixed with the ZIP load

2022-04-07 00:48 UTC, jd-lara commented on src/base/perturbations.jl
> +    # TODO: Change ConstantImpedance and ConstantPower
Remove stale `TODO`

2022-04-07 00:48 UTC, jd-lara commented on src/base/perturbations.jl
> +    @info "Changing load at bus $(PSY.get_name(wrapped_zip)) $(pert.signal) to $(pert.ref_value)"
This info is outside of the function calls. It won't' be called ever. Either move to the top or inside of the callback

2022-04-07 00:48 UTC, jd-lara commented on src/base/perturbations.jl
> +    @info "Removing load power values from ZIP load at $(PSY.get_name(wrapped_zip))"
same comment as above

2022-04-07 00:48 UTC, jd-lara commented on src/base/perturbations.jl
> +        )
add an assertion that the size of wrapped_device has to be  == 1

2022-04-07 00:48 UTC, jd-lara commented on src/models/device.jl
> +    mdl_static_load!(voltage_r, voltage_i, current_r, current_i, device, ZIPLoad())
we don't need to instantiate a `ZIPLoad()` anymore here. Since this will dispatch on the device type `ZIPLoadWrapper`. We don't even need to have a separate function call for `mdl_static_load!` we can call that code directly here.

2022-04-07 00:48 UTC, jd-lara commented on src/models/load_models.jl
> +function mdl_static_load!(
This can be removed now. It isn't being called

2022-04-07 00:48 UTC, jd-lara commented on src/models/load_models.jl
> +    ::ZIPLoad,
no need to dispatch on `ZIPLoad`

2022-04-07 00:48 UTC, jd-lara commented on src/base/load_categories.jl
>  struct ConstantCurrent <: LoadCategory end
all of these can be removed now

2022-04-07 00:48 UTC, jd-lara commented on src/base/load_categories.jl
>  const LOAD_MAP = Dict(
The load map can also be removed

2022-04-08 22:04 UTC, jd-lara commented on src/base/perturbations.jl
> +        )
@rodrigomha this comment needs to be addressed

2022-04-08 22:21 UTC, rodrigomha commented
I will add yesterday test for testing the three different load types. We can generate the traces later in PSSE.

2022-04-10 19:40 UTC, jd-lara approved these changes

2022-04-10 19:41 UTC, merged