Add DERA model
NREL-SIIP/PowerSimulationsDynamics.jl pull request #226
Opened 2022-05-20 18:26 UTC by m-bossart

questions on current implementation:

- Add non-default mass matrix entries.
- Where does current limit logic, voltage trip logic, frequency trip logic belong?
- Remove additional states based on combinations of flags? (more complex implementation) 
- Is the use of inner vars appropriate?

2022-06-30 16:21 UTC, m-bossart commented
This PR requires https://github.com/NREL-SIIP/PowerSystems.jl/pull/901

2022-06-30 16:44 UTC, rodrigomha requested changes
Besides the individual comments. We may need to talk with Gustavo before merging if it makes sense based on his experience to make some functions use mass_matrix approach if for those states is common to have a time constant equals to zero.

2022-06-30 16:44 UTC, rodrigomha commented on src/base/device_wrapper.jl
> +    device::PSY.ThermalStandard,
Should this be any `PSY.StaticInjection`? or at least `PSY.Generator`

2022-06-30 16:44 UTC, rodrigomha commented on src/base/device_wrapper.jl
> +        PSY.ThermalStandard,
same here?

2022-06-30 16:44 UTC, rodrigomha commented on src/initialization/init_device.jl
> +    device_states = zeros(PSY.get_n_states(dynamic_wrapper))    #TODO ask -- why does this method work with the wrapper in stead of the device?
To remove the comment: There is an overload of the PSY function. It is in line 251 in master in `dynamic_wrapper.jl`

2022-06-30 16:44 UTC, rodrigomha commented on src/models/device.jl
> +    _mdl_ode_AggregateDistributedGenerationA!(
This idea of dispatch is looking good for me. It is consistent of what we currently use for PSS. We may need to revisit this dispatch idea in the future though @jd-lara ?

2022-06-30 16:44 UTC, rodrigomha commented on src/models/saturation_models.jl
> +    if local_I < I_max #fixed typo
thanks, you can remove the comment

2022-06-30 17:01 UTC, m-bossart commented on src/base/device_wrapper.jl
> +    device::PSY.ThermalStandard,
I originally had it as `PSY.StaticInjection` but there was ambiguity because there is another method which dispatches on `PSY.Source` and `PSY.DynamicInjection`. I can change it to `PSY.Generator`

2022-06-30 17:03 UTC, m-bossart commented
I did a rebase yesterday before this latest round of changes. So I think it should be OK?

2022-06-30 19:38 UTC, tavovalmo commented
> Besides the individual comments. We may need to talk with Gustavo before merging if it makes sense based on his experience to make some functions use mass_matrix approach if for those states is common to have a time constant equals to zero. Any comments here @tavovalmo ?

Great job Matt! I think that all lab blocks in this model should use the mass_matrix approach as users may set the time constants to zero. Generally I use even a small value to represent the transducers.

2022-06-30 20:54 UTC, m-bossart commented
@tavovalmo or @rodrigomha What is a good example for the mass matrix implementation of the lag blocks?

2022-07-01 17:14 UTC, tavovalmo commented
> @tavovalmo or @rodrigomha What is a good example for the mass matrix implementation of the lag blocks?

You can check the EXST1 model in avr_models.jl. Rodrigo explained to me how to do it.

2022-07-01 19:15 UTC, m-bossart commented
I changed most of the states to mass matrix implementation. I left `Ip` and `Iq` as is because the PSSE documentation explicitly requires time constant greater than zero for those states. I left the `DynamicWrapper` dispatch as is because @jd-lara mentioned he had a fix in mind.

2022-07-05 21:49 UTC, rodrigomha commented on src/models/device.jl
> +    Freq_Flag = PSY.get_Freq_Flag(get_device(dynamic_device))
this should be `dera`

2022-07-05 21:51 UTC, rodrigomha commented
This is looking good. I think once we release the updated version of the struct in PSY this should be ok.

2022-07-07 01:38 UTC, m-bossart commented on src/base/device_wrapper.jl
> +        PSY.ThermalStandard,
@jd-lara  Not sure where we left this - you mentioned you had a fix for the ambiguity error. Is there anything else that needs to be done from my side.

2022-08-01 19:03 UTC, merged