Add current post process for ACBranches
NREL-SIIP/PowerSimulationsDynamics.jl pull request #253
Opened 2022-06-15 21:32 UTC by rodrigomha

This is a temporal solution. We will need a way of dispatching properly once we redo the API.

Note that this method allows to use `get_active_current_series(results, LineName)` to obtain them.

The voltage obtained in `post_proc_voltage_current_series` is taken using the `from` bus, so if you use `get_activepower_series(results, LineName)` it will compute the active power going through the series part of the `ACBranch` measured on the `from` bus.

Closes #224

2022-06-16 00:26 UTC, m-bossart commented
My only concern here is that there isn't a way to get the current/power in the opposite direction (starting at the `to` bus). If that is the case I guess the only option is to change how the system is specified in terms of which bus if `from` and which is `to`? Seems like there should be a better way even for this temporary solution

2022-06-16 00:26 UTC, m-bossart commented
My only concern here is that there isn't a way to get the current/power in the opposite direction (starting at the `to` bus). If that is the case I guess the only option is to change how the system is specified in terms of which bus if `from` and which is `to`? Seems like there should be a better way even for this temporary solution

2022-06-16 00:27 UTC, jd-lara commented
@m-bossart if we want to do that then the requirement needs to be like PSSe where the user needs to specify the From or To direction.

2022-06-16 00:30 UTC, rodrigomha commented
> My only concern here is that there isn't a way to get the current/power in the opposite direction (starting at the `to` bus). If that is the case I guess the only option is to change how the system is specified in terms of which bus if `from` and which is `to`? Seems like there should be a better way even for this temporary solution

I mean the current in the opposite direction is the same, you can just multiply by -1. The power is a different story. In that case, we would probably want to create an additional function only for lines of the form `get_branch_activepower_series` or something like that, and specify using a symbol `:to` `:from`, or something like that. It would be of the form:
`get_branch_activepower_series(results, LineName, :to, dt)`

2022-06-16 00:34 UTC, rodrigomha commented
It seems that we need two functions then. One for the series current is okay. But if we want the total current (power) flowing into (or out) a bus (from a branch), we need to consider the capacitance. @m-bossart Is this something that you want?

2022-06-16 00:39 UTC, jd-lara requested changes
Requires passing argument From - To before merge.  Needs to specify the point of measurement.

2022-06-16 14:32 UTC, m-bossart commented
@rodrigomha Ideally yes. I'd like to specify the direction and also the total current (including the capacitance).

2022-06-17 23:35 UTC, rodrigomha commented
@m-bossart @jd-lara still need to do more changes, but will do after vacations.

Matt, do you also need a function to obtain total nodal current too right? That is easy to implement later by just adding both shunt and series current.

TODO: 
- [ ] Dispatch for Transformer2W to compute shunt current.
- [ ] Check that the computation is correct using the known formula `Q = - V^2/C`

2022-06-17 23:37 UTC, jd-lara commented
@rodrigomha are you thinking of implementing a nodal current post-processing separate from the line current?

2022-06-21 21:54 UTC, jd-lara commented
we should split this effort in branch/nodal currents

2022-07-05 22:00 UTC, rodrigomha commented
Closing this one to split in future two PRs

2022-07-05 22:00 UTC, closed without merging