add plot util for getting voltage angle
NREL-SIIP/PowerSimulationsDynamics.jl pull request #84
Opened 2021-06-14 21:07 UTC by m-bossart

2021-06-14 22:36 UTC, jd-lara commented on src/PowerSimulationsDynamics.jl
>  export get_voltagemag_series
We should also spell `voltage_magnitude`

2021-06-14 22:37 UTC, jd-lara requested changes
Can you make the requested name changes to the function names and format correctly the code please?

2021-06-14 23:19 UTC, m-bossart commented
so the functions should be named `get_voltage_magnitude_series` and `get_voltage_angle_series`?

2021-06-14 23:20 UTC, jd-lara commented
> so the functions should be named `get_voltage_magnitude_series` and `get_voltage_angle_series`?

Yes please

2021-06-15 01:19 UTC, rodrigomha commented on test/test_case01_OMIB.jl
> +        series2 = get_voltage_magnitude_series(sim, 102)
Can you test the function? You can add `series3 = get_voltage_angle_series(sim, 102)`.

2021-06-15 01:20 UTC, rodrigomha commented on test/test_case01_OMIB.jl
> +        series2 = get_voltage_magnitude_series(sim, 102)
Only do it in Test01

2021-06-15 16:52 UTC, jd-lara commented on test/test_case01_OMIB.jl
> +        series2 = get_voltage_magnitude_series(sim, 102)
```suggestion
        series2 = get_voltage_magnitude_series(sim, 102)
        series3 = get_voltage_angle_series(sim, 102)
```

2021-06-15 16:53 UTC, merged